<div data-role="page" id="dashboard-page">
    <div date-role="header">
        <h1>Bethel First Impressions</h1>
    </div>
    <div data-role="content">
        <div id="layout">
            <table>
                <thead>
                    <tr>
                        <td>Attendance</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>0-9 months</td>
                        <td><input type="text" class="attendance" /></td>
                        <td>Auditorium</td>
                        <td><input type="text" class="attendance" /></td>
                    </tr>
                    <tr>
                        <td>10-18 months</td>
                        <td><input type="text" class="attendance" /></td>
                    </tr>
                    <tr>
                        <td>19-27 months</td>
                        <td><input type="text" class="attendance" /></td>
                    </tr>
                    <tr>
                        <td>3-4 year olds</td>
                        <td><input type="text" class="attendance" /></td>
                    </tr>
                    <tr>
                        <td>5-Kindergarten</td>
                        <td><input type="text" class="attendance" /></td>
                    </tr>
                    <tr>
                        <td>1-2 Grade</td>
                        <td><input type="text" class="attendance" /></td>
                    </tr>
                    <tr>
                        <td>3-4 Grade</td>
                        <td><input type="text" class="attendance" /></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>