<?php echo $this->doctype(); ?>

<html lang="en">

    <head>
        <title>Bethel First Impressions</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . "js/jquery.mobile/jquery.mobile-1.4.5.min.css");

        echo $this->headScript()
                ->prependFile($this->basePath() . "js/jquery-2.1.3.min.js")
                ->appendFile($this->basePath() . "js/jquery.mobile/jquery.mobile-1.4.5.min.js")
                ->appendFile($this->basePath() . "js/position.js");
        ?>

        <style>
            h1 {
                text-align: center;
            }

            #layout {
                padding: 50px 50px;
            }

            .positions {
                width: 100px !important;
                background: #22aadd !important;
            }

            .positions:hover {
                cursor: pointer;
            }

        </style>

    </head>

    <body>

        <?php echo $this->content; ?>

    </body>
</html>
